In [ ]:
%load_ext autoreload
%autoreload 2

In [ ]:
from pathlib import Path
import pandas as pd
from ecephys_analyses.data import paths

from ecephys import sglx_utils


# Stim_times.txt

In [ ]:
### Allan

In [ ]:
# simple conditions

In [ ]:
conditions =  [
#     '3-5-2021_g0_imec0',
#     '3-5-2021_g0_imec1',
    '3-5-2021_g2_imec0',
    '3-5-2021_g2_imec1',
    '3-5-2021_g3_imec0',
    '3-5-2021_g3_imec1',
#     '3-5-2021_g4_imec0',
#     '3-5-2021_g4_imec1',
#     '3-5-2021_g5_imec0',
#     '3-5-2021_g5_imec1',
#     '3-5-2021_g6_imec0',
#     '3-5-2021_g6_imec1',
]
print(conditions)


In [ ]:
for cond in conditions:
    path = paths.get_datapath('Allan', cond, 'dummy')
    print(path.parent)
    path.parent.mkdir()

In [ ]:
# Combined

In [ ]:
combined_cond = '3-5-2021_g2-3_imec1'
conditions =  paths.load_datapath_yaml()['Allan'][combined_cond]
print(conditions)


In [ ]:
dfs = []
start_time = 0
for cond in conditions:
    print(cond, 'start time', start_time)
    path = paths.get_datapath('Allan', cond, 'stim_times.csv')
    df = pd.read_csv(path)
    df['sglx_stim_time'] = df['sglx_stim_time'] + start_time
    dfs.append(df)
    binpaths = paths.get_sglx_style_datapaths('Allan', cond, 'ap.bin', catgt_data=True)
    assert len(binpaths) == 1
    start_time = float(sglx_utils.get_meta(binpaths[0])['fileTimeSecs'])
df_combined = pd.concat(dfs)
    
#     end_time 
#     df
#     print(path.exists())
#     print(path)
    

In [ ]:
save_path = paths.get_datapath('Allan', combined_cond, 'stim_times.csv')
save_path

In [ ]:
df_combined.to_csv(save_path, index=False)

In [ ]:
### EUGENE

In [ ]:
eugene = pd.read_excel('Eugene.xlsx', engine='openpyxl')

In [ ]:
eugene.columns

In [ ]:
eugene.columns = 'datapath', 'state', 'depth', 'stimpath', 'N_trials', 'trials_reordered_BL'

In [ ]:
eugene['datapath'][0:1].values

In [ ]:
conditions = paths.get_conditions('Eugene', 'eStim')

In [ ]:
eugene[0:10]

In [ ]:
# add condition dir to run path

for cond in conditions: 
    pathname = paths.get_sglx_style_datapaths('Eugene', cond, 'ap.bin')[0]
    rundir = pathname.parents[1]
    run = rundir.name
    for i, row in eugene.iterrows():
        path = row['datapath']
        assert rundir not in eugene.columns or eugene.iloc[i, 'rundir'] is None 
        if run in path:
            eugene.loc[i, 'rundir'] = rundir
            eugene.loc[i, 'condition'] = cond.split('_imec')[0]

In [ ]:
eugene['condition']

In [ ]:
import numpy as np

# for i, row in eugene.iterrows():
for cond in conditions:
    for i, row in eugene.iterrows():
        if row['condition'] not in cond:
            continue
        stimpath = row['stimpath'].split('CNPIX6-Eugene')[1].replace('\\', '/').replace("'", '')

        stimpath = Path('/Volumes/neuropixel/Data/CNPIX6-Eugene' + stimpath)
    #     print(stimpath, stimpath.exists())

        stim_times = pd.read_csv(stimpath, header=None)

        df = pd.DataFrame({'sglx_stim_time': np.concatenate(stim_times.values), 'stim_state': row['state']})
        print(df[0:5])

    #     dfpath = path.get_filename()
        df_path = paths.get_datapath('Eugene', cond, 'stim_times.csv')
        print(df_path)

        df.to_csv(df_path, index=False)

    #     if i > 3:
    #         break
    #     stimtimes = 

In [ ]:
### Alessandro

In [ ]:
aless = pd.read_excel('Alessandro stim location.xlsx', engine='openpyxl')

In [ ]:
aless.columns

In [ ]:
aless.columns = 'datapath', 'state', 'depth', 'stimpath', 'N_trials', 'trials_reordered_BL'

In [ ]:
aless['datapath'][0:1].values

In [ ]:
conditions = paths.get_conditions('Alessandro', 'eStim')

In [ ]:
aless[0:10]

In [ ]:
# add condition dir to run path

for cond in conditions: 
    pathname = paths.get_sglx_style_datapaths('Alessandro', cond, 'ap.bin')[0]
    rundir = pathname.parents[1]
    run = rundir.name
    for i, row in aless.iterrows():
        path = row['datapath']
        assert rundir not in aless.columns or aless.iloc[i, 'rundir'] is None 
        if run in path:
            aless.loc[i, 'rundir'] = rundir
            aless.loc[i, 'condition'] = cond

In [ ]:
aless

In [ ]:
aless['condition']

In [ ]:
aless['rundir'][0]

In [ ]:
aless['stimpath'][0]

In [ ]:
import numpy as np

# for i, row in eugene.iterrows():
for cond in conditions:
    for i, row in aless.iterrows():
        if row['condition'] not in cond:
            continue
        stimpath = row['stimpath'].split('CNPIX5-Alessandro')[1].replace('\\', '/').replace("'", '')

        stimpath = Path('/Volumes/neuropixel/Data/CNPIX5-Alessandro' + stimpath)
        print(stimpath, stimpath.exists())

        stim_times = pd.read_csv(stimpath, header=None)

        df = pd.DataFrame({'sglx_stim_time': np.concatenate(stim_times.values), 'stim_state': row['state']})
        print(df[0:5])

    #     dfpath = path.get_filename()
        df_path = paths.get_datapath('Alessandro', cond, 'stim_times.csv')
        print(df_path)

        df_path.parent.mkdir()
        df.to_csv(df_path, index=False)

    #     if i > 3:
    #         break
    #     stimtimes = 

In [ ]:
# Giuseppe Combined

In [ ]:
combined_cond = '8-31-2020_REMmerged_imec0'
conditions =  paths.load_datapath_yaml()['Alessandro'][combined_cond]
# conds = paths.get_sglx_style_datapaths('Giuseppe', '12-27-2020_Wake_NREM_REM_depth1.5_imec0', 'dummy')
print(conditions)

In [ ]:
# dfs = []
# start_time = 0
# for cond in conditions:
#     path = (paths.get_datapath('Alessandro', cond, 'stim_times.csv'))
#     df = pd.read_csv(path)
#     df['sglx_stim_time'] = df['sglx_stim_time'] + start_time
#     dfs.append(df)
# #     binpaths = paths.get_sglx_style_datapaths('Giuseppe', cond, 'ap.bin', catgt_data=True)
#     assert len(binpaths) == 1
#     start_time = float(sglx_utils.get_meta(binpaths[0])['fileTimeSecs'])
# df_combined = pd.concat(dfs)
# df_combined
    
# #     end_time 
# #     df
# #     print(path.exists())
# #     print(path)
    

In [ ]:
# Giuseppe

In [ ]:
# Combined

In [ ]:
combined_cond = '12-27-2020_Wake_NREM_REM_depth1.5_imec0'
conditions =  paths.load_datapath_yaml()['Giuseppe'][combined_cond]
# conds = paths.get_sglx_style_datapaths('Giuseppe', '12-27-2020_Wake_NREM_REM_depth1.5_imec0', 'dummy')
# conds

In [ ]:
dfs = []
start_time = 0
for cond in conditions:
    path = (paths.get_sglx_style_datapaths('Giuseppe', cond, 'dummy', catgt_data=True)[0].parents[1])/'stim_times.csv'
    df = pd.read_csv(path)
    df['sglx_stim_time'] = df['sglx_stim_time'] + start_time
    dfs.append(df)
    binpaths = paths.get_sglx_style_datapaths('Giuseppe', cond, 'ap.bin', catgt_data=True)
    assert len(binpaths) == 1
    start_time = float(sglx_utils.get_meta(binpaths[0])['fileTimeSecs'])
df_combined = pd.concat(dfs)
    
#     end_time 
#     df
#     print(path.exists())
#     print(path)
    

In [ ]:
save_path = paths.get_datapath('Giuseppe', combined_cond, 'stim_times.csv')
save_path

In [ ]:
df_combined.to_csv(save_path, index=False)

# Channel depths

In [ ]:
# metapath = Path('/Volumes/scratch/neuropixels/data/tom/catgt/CNPIX4-Doppio/3-17-2020/catgt_3-17-2020_g0/3-17-2020_g0_imec0/3-17-2020_g0_tcat.imec0.ap.meta')
metapath = Path('/Volumes/scratch/neuropixels/data/tom/catgt/CNPIX8-Allan/3-1-2021/catgt_3-1-2021_C_g0/3-1-2021_C_g0_imec1/3-1-2021_C_g0_tcat.imec1.ap.meta')

In [ ]:
from ecephys_analyses.data.utils import depth_from_channel

depth_from_channel(metapath, [287, 176, 291])
# (array([286]),)
# (array([175]),)
# (array([290]

# Copy concatenated hypnograms to condition dir

In [ ]:
from pathlib import Path
import pandas as pd
from ecephys_analyses.data import paths
from ecephys import scoring


In [ ]:
condition_groups = [
#     ('Doppio', 'SD'),
#     ('Allan', 'SD'),
#     ('Luigi', 'SD'),
    
]

data_conditions = []
for subject, condition_group in condition_groups:
    data_conditions += [
        (subject, cond)
        for cond in paths.get_conditions(subject, condition_group)
    ]
print(f'Data condition N={len(data_conditions)} (Looks good?): {data_conditions}')

In [ ]:
for subject, condition in data_conditions:
    hyp_paths = paths.get_hypno_datapaths(subject, condition)
    print(subject, condition)
    for prb in ['imec0', 'imec1']:
        try:
            print(f'Try loading hyp saved for {prb}...', end='')
            imec_hyp_paths = [
                Path(str(p).replace('imec0', 'imec1').replace('imec1', prb))
                for p in hyp_paths
            ]
            print(imec_hyp_path)
            hyp = scoring.load_consecutive_visbrain_hypnograms(
                imec_hyp_paths
            )
            found=True
            print('Found it!')
            break
        except FileNotFoundError:
            print('not found')
            found=False
            continue
    if not found:
        continue
    print("Save in condition dir")
    savepath = paths.get_datapath(subject, condition, 'hypnogram.csv')
    savepath.parent.mkdir(exist_ok=True)
    print(savepath)
    hyp.to_csv(savepath, index=False)
    print("Done")
    print('\n\n')
        

In [ ]:
hyp = scoring.load_consecutive_visbrain_hypnograms(
    paths.get_hypno_datapaths('Allan', 'baseline-sleep-2h-circadian-match_imec1')
)

In [ ]:
hyp

# Change format of hypnogram  (hypnogram.txt to hypnogram.csv in same dir)

In [ ]:
root = Path('/Volumes/scratch/neuropixels/data/tom/catgt/CNPIX10-Charles/recovery-sleep-2h_imec0/')
src_filename = 'hypnogram.txt'
tgt_filename = 'hypnogram.csv'

hyp = scoring.load_visbrain_hypnogram(root/src_filename)
hyp.to_csv(root/tgt_filename, index=False)




# Copy concatenated hypnograms to "multiple" condition dir

In [ ]:
from pathlib import Path
import pandas as pd
from ecephys_analyses.data import paths
from ecephys import scoring


In [ ]:
condition_groups = [
#     ('Doppio', 'SD'),
#     ('Allan', 'SD'),
#     ('Luigi', 'SD'),
    ('Charles', 'SD'),
]

root_key = 'sleep-homeostasis'

data_conditions = []
for subject, condition_group in condition_groups:
    data_conditions += [
        (subject, cond)
        for cond in paths.get_conditions(subject, condition_group)
    ]
print(f'Data condition N={len(data_conditions)} (Looks good?): {data_conditions}')

In [ ]:
from ecephys_analyses.data.paths import get_subconditions, is_combined_condition
from ecephys.scoring import load_consecutive_csv_hypnograms

for subject, condition in data_conditions:

    if is_combined_condition(subject, condition):
        subconditions = get_subconditions(subject, condition)
        hyp = load_consecutive_csv_hypnograms(
            [
                paths.get_datapath(subject, subcondition, 'hypnogram.csv', root_key=root_key)
                 for subcondition in subconditions
            ],
            conditions = subconditions,
        )
        print("Save in condition dir")
        savepath = paths.get_datapath(subject, condition, 'hypnogram.csv', root_key=root_key)
        savepath.parent.mkdir(exist_ok=True)
        print(savepath)
        hyp.to_csv(savepath, index=False)
        print("Done")
        
    # subconditions = get_subconditions('Doppio', 'baseline-sleep-2h-circadian-match_imec1')
    else:
        print(f"Pass {subject} {condition}: Not 'combined' condition")


In [ ]:
hyp